
name: hosts

on:
  schedule:
    # Runs at 00:00 UTC every day.
    - cron: '0 0,6,12,18 * * *'

  workflow_dispatch:
    inputs:
      dns:
        description: 'DNS provider'
        required: true
        default: 'Cloudflare'
        type: choice
        options:
        - 'Cloudflare'
        - 'Google'
        - 'Aliyun'
      type:
        description: 'Record type'
        required: true
        default: 'A'
        type: choice
        options:
        - 'A'
        - 'AAAA'

jobs:
  hosts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: Set up Python 3
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'
          
      - name: Init Env
        run : |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          sudo timedatectl set-timezone "Asia/Shanghai"
          python -m pip install --upgrade pip setuptools
          python -m pip install requests

      - name: Generate Hosts
        run: python hosts.py --create --dns ${{ inputs.dns || 'Cloudflare' }} --type ${{ inputs.type || 'A' }} --create --output hosts

      - name: Check and Push
        run: |
          if [ -n "$(git status -s | grep hosts)" ]; then
            git add hosts
            git commit -m "update $(date '+%Y-%m-%d %H:%M:%S')"
            git push -f
          fi

